name: ci

on:
  release:
    types: [created]

jobs:
  bazel_go:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set Docker tags
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Bazel/Go
        uses: docker/build-push-action@v2
        with:
          context: bazel/go
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: quay.io/peridot/bazel-go:${{ env.tag }}
  bazel_node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set Docker tags
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build and push Bazel/Node
        uses: docker/build-push-action@v2
        with:
          context: bazel/node
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: quay.io/peridot/bazel-node:${{ env.tag }}
  build_base_rhel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set Docker tags
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build and push Build Base
        uses: docker/build-push-action@v2
        with:
          context: build
          file: build/rhel.Dockerfile
          platforms: linux/amd64,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: quay.io/peridot/build-base:${{ env.tag }}
  ci_base:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set Docker tags
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build and push CI Base
        uses: docker/build-push-action@v2
        with:
          context: ci
          platforms: linux/amd64
          push: true
          tags: quay.io/peridot/ci:${{ env.tag }}
  spicedb:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1 
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

      - name: Set Docker tags
        run: |
          echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      
      - name: Build and push SpiceDB
        uses: docker/build-push-action@v2
        with:
          context: spicedb
          platforms: linux/amd64
          push: true
          tags: quay.io/peridot/spicedb:${{ env.tag }}